yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <span style="color:black">Рамазан Гилязев.</span></p>

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: #A0522D">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <span style="color:#c8a98f">Сайт Рамазана Гилязева</span>
          </a>
    <ul class="nav nav-pills">
        <li class="nav-item" >
          <a class="nav-link {% if view_name  == 'about:author' %}active{% endif %}"
             href="{% url 'about:author' %}" style = "color:#c8a98f" >Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'about:tech' %}active{% endif %}"
             href="{% url 'about:tech' %}" style = "color:#c8a98f" >О сайте</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'posts:post_create' %}active{% endif %}"
          href="{% url 'posts:post_create' %}" >Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:password_change_form' %}active{% endif %}"
          href="{% url 'users:password_change_form' %}">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:logout' %}active{% endif %}"
          href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:login' %}active{% endif %}"
          href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light {% if view_name  == 'users:signup' %}active{% endif %}"
          href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>

        </div>
</nav>

{% endwith %}