yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """ Group of posts organization. """
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    """ Creating a post with useful and necessary information. """

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        on_delete=models.SET_NULL,
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField()
    created = models.DateTimeField("Дата публикации", auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        """ Post form for creating a form for working with the User model. """
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }
        help_texts = {
            'text': 'Текст нового комментария',
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User
from .paginator_mod import paginate_page
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required


def index(request):
    """ Creates necessary link. """

    posts = Post.objects.all()
    page_obj = paginate_page(posts, request)
    context = {'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """ Sorts posts in appropriate groups. """

    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group)
    page_obj = paginate_page(posts, request)
    context = {'group': group, 'page_obj': page_obj}
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """ User's posts in his/her profile. """

    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = paginate_page(posts, request)
    context = {
        "author": author,
        'page_obj': page_obj
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """ Special information about post. """

    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    count_post = post.author.posts.count()
    comments = post.comments.select_related('author')
    context = {
        'author': post.author,
        'post': post,
        'count_post': count_post,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """ Gives us possibility to create new post. """

    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    """ Gives us possibility to edit post. """
    post_object = get_object_or_404(
        Post,
        id=post_id,
        author=request.user
    )
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post_object
    )
    if form.is_valid():
        form.save()
        if post_object.author == request.user:
            return redirect('posts:post_edit', post_id)
        if post_object.author != request.user:
            return redirect('posts/post_detail.html', post_id)
    context = {
        'form': form,
        'True': True,
        'post': post_object,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(
        request,
        'posts/includes/comments.html',
        {
            'form': form,
            'post': post,
        }
    )

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% if form.instance.pk %}
          Редактировать запись
        {% else %}
          Новый пост
        {% endif %}
      </div>
      <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3 p-3"{% if field.field.required %}
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
            </label>
            <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
            </div>
          </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if post %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% load thumbnail %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
{% for post in page_obj %}
<article>
  <ul>
    <li>Автор: {{ post.author.get_full_name }} </li>

    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  {% thumbnail post.image "960x960" crop="top" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>{{ post.text }}</p>
</article>
{% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
Последние обновления на сайте
{% endblock %}
{% block content %}
<h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
{% include 'posts/post.html' %}
{% if not forloop.last %}
<hr>{% endif %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post.html
{% load thumbnail %}
<article>
<ul>
  <li>
    Автор: {{ post.author.get_full_name }}
  </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a><br>
    {% if post.group is not group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group.title }}" </a>
      {% endif %}
</ul>
  {% thumbnail post.image "1400x960" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
<p>
  {{ post.text|linebreaksbr }}
</p>
</article>

yatube/templates/posts/post_detail.html
{%extends "base.html"%}
    {%block title%}Пост {{ post|truncatechars:30 }}{%endblock%}
    {% load thumbnail %}
    {% load user_filters %}
    {%block content%}
        <div class="row">
            <aside class="col-12 col-md-3">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
                <li class="list-group-item">
                  Группа:
                  {% if post.group %}
                    {{ post.group }}
                  {% else %}
                    ---Пусто---
                  {% endif %}
                  {% if post.group %}
                    <a href="{% url 'posts:group_list' post.group.slug %}">
                      все записи
                    </a>
                  {% endif %}
                </li>
                <li class="list-group-item">
                  Автор:
                  {% if post.author.get_full_name %}
                    {{ post.author.get_full_name }}
                  {% else %}
                    {{ post.author }}
                  {% endif %}
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  Всего постов автора:  <span >{{ post_count }}</span>
                </li>
                <li class="list-group-item">
                  <a href="{% url 'posts:profile' post.author %}">
                    все посты пользователя
                  </a>
                </li>
              </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x960" crop="top" upscale=True as im %}
                     <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if post.author.pk == request.user.pk %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
            Редактировать запись
          </a>
        {% endif %}
        </button>
                 <div class="col-md-9">
        {% include 'posts/includes/comments.html' %}
      </div>
        </article>
          </div>
        {% if not forloop.last %} <hr> {% endif %}
        {% include 'posts/includes/paginator.html' %}
{%endblock%}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}
  Профайл пользователя {{ author }}
{% endblock %}

{% load thumbnail %}

{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count }} </h3>
{% for post in page_obj %}
<article>
    <ul>
        <li>
            Автор: {{ post.author.get_full_name }}
        </li>
        <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
    </ul>
    {% thumbnail post.image "960x960" crop="top" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
    <p>
        {{ post.text }}
    </p>
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
</article><br>
  {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}

{% include 'posts/includes/paginator.html' %}
{% endblock %}